#!/bin/sh
# Pure helpers for the status page. render_status writes the page to stdout
# from the stubs and the services file; build.sh and check.sh decide what to
# do with the result.

# stub_field FILE KEY
# Print the value of "KEY: value" in a stub, or nothing.
stub_field() {
  awk -v k="$2" '
    index($0, k ":") == 1 { v = substr($0, length(k) + 2); sub(/^[ \t]+/, "", v); sub(/[ \t\r]+$/, "", v); print v; exit }
  ' "$1"
}

# render_status STUBS_DIR [SERVICES_FILE]
# STUBS_DIR holds one FEATURE.md per feature with lines "name:", "state:",
# "issue:" and "note:". SERVICES_FILE holds lines "service: state".
render_status() {
  rs_stubs=$1
  rs_services=$2

  printf '# Status\n\n'
  printf 'One screen on where the project stands, for an agent starting cold. Generated from `status/stubs/` by `sh status/build.sh`; CI fails when it is stale. Do not edit this file; edit a stub.\n\n'

  printf '## Features\n\n'
  printf '| Feature | State | Issue | Note |\n'
  printf '|---|---|---|---|\n'
  for rs_f in "$rs_stubs"/*.md; do
    [ -e "$rs_f" ] || continue
    rs_name=$(stub_field "$rs_f" name)
    [ -n "$rs_name" ] || rs_name=$(basename "$rs_f" .md)
    rs_state=$(stub_field "$rs_f" state)
    [ -n "$rs_state" ] || rs_state="not started"
    rs_issue=$(stub_field "$rs_f" issue)
    rs_note=$(stub_field "$rs_f" note)
    printf '| %s | %s | %s | %s |\n' "$rs_name" "$rs_state" "$rs_issue" "$rs_note"
  done

  if [ -n "$rs_services" ] && [ -f "$rs_services" ]; then
    printf '\n## Services\n\n'
    printf '| Service | State |\n'
    printf '|---|---|\n'
    tr -d '\r' < "$rs_services" | awk -F': *' 'NF >= 2 && $1 !~ /^[ \t]*#/ { printf "| %s | %s |\n", $1, $2 }'
  fi

  printf '\n## Not done\n\n'
  rs_any=0
  for rs_f in "$rs_stubs"/*.md; do
    [ -e "$rs_f" ] || continue
    rs_state=$(stub_field "$rs_f" state)
    [ -n "$rs_state" ] || rs_state="not started"
    [ "$rs_state" = "done" ] && continue
    rs_name=$(stub_field "$rs_f" name)
    [ -n "$rs_name" ] || rs_name=$(basename "$rs_f" .md)
    printf -- '- %s (%s)\n' "$rs_name" "$rs_state"
    rs_any=1
  done
  [ "$rs_any" = 1 ] || printf 'Nothing. Every feature is done.\n'
}
